package:
  name: torch_formatter
  version: 0.0.3

build:
  number: 1

requirements:
  build:
    - python~=3.8
    - setuptools
  run:
    - python~=3.8
about:
  summary: Fancy PyTorch education output for Jupyter