package:
  name: chained
  version: 0.0.1

build:
  number: 1

requirements:
  build:
    - python~=3.8
    - setuptools
  run:
    - python~=3.8
about:
  summary: Fancy PyTorch education output for Jupyter